#Musica 'rirura_2 new.mp3' salva no diretorio 'rirura_2 new'

-0.12, 0.01; 3.0331; C
-0.12, 0.01; 0.3831; C
0.13, 0.02; 1.3003; B
0.13, 0.02; 0.3483; B
-0.12, 0.00; 1.3816; C
-0.12, 0.00; 0.4296; C
0.11, 0.01; 1.3003; B
0.11, 0.01; 0.4063; B
-0.14, 0.00; 1.3468; C
-0.14, 0.00; 0.4412; C
0.12, 0.02; 1.3235; B
0.12, 0.02; 0.4296; B
-0.15, 0.01; 1.3119; C
-0.15, 0.01; 0.3831; C
0.09, 0.02; 1.3816; B
0.09, -0.06; 0.4992; B
-0.15, 0.01; 1.2190; C
-0.15, 0.01; 0.5224; C
0.11, 0.01; 1.2655; B
0.11, -0.12; 0.4992; B
-0.12, 0.02; 1.2307; C
-0.12, -0.07; 0.4760; C
0.12, 0.03; 1.2307; B
0.12, -0.11; 0.4876; B
-0.12, 0.04; 1.3119; C
-0.11, -0.06; 0.4760; C
0.11, 0.03; 1.2423; B
0.12, -0.13; 0.4876; B
-0.00, -0.08; 1.3235; A
0.00, 0.06; 0.8127; D
-0.11, 0.02; 0.8824; C
-0.13, -0.01; 0.8707; C
-0.03, 0.07; 0.7895; D
-0.01, 0.07; 0.7779; D
0.12, 0.00; 1.0565; B
0.12, 0.00; 0.7663; B
0.02, -0.08; 0.9868; A
0.02, -0.08; 0.8011; A
0.12, -0.02; 0.9868; B
0.12, -0.02; 0.6618; B
0.00, 0.08; 1.0449; D
0.00, 0.08; 0.7430; D
-0.15, 0.00; 0.9985; C
-0.15, 0.00; 0.7547; C
0.01, -0.08; 0.9520; A
0.00, -0.07; 0.4180; A
-0.00, -0.06; 0.9172; A
-0.00, -0.06; 0.4760; A
-0.00, -0.06; 0.4296; A
-0.00, 0.08; 1.2887; D
-0.00, 0.08; 0.3947; D
0.00, -0.10; 1.3584; A
0.00, -0.10; 0.3947; A
-0.01, 0.08; 1.3584; D
-0.01, 0.08; 0.3831; D
-0.01, -0.10; 1.3700; A
-0.01, -0.10; 0.4063; A
-0.01, 0.07; 1.3003; D
-0.01, 0.07; 0.4180; D
-0.01, -0.09; 1.3468; A
-0.01, -0.09; 0.4180; A
-0.01, 0.08; 1.3700; D
-0.00, -0.10; 0.8591; A
-0.12, -0.03; 0.9056; C
-0.12, -0.03; 0.4063; C
-0.01, 0.07; 1.3003; D
-0.01, 0.07; 0.3831; D
0.12, -0.00; 1.3816; B
0.12, -0.00; 0.3831; B
0.01, -0.09; 1.3351; A
0.01, -0.09; 0.4180; A
0.11, -0.01; 1.3351; B
0.11, -0.01; 0.4063; B
-0.01, 0.06; 1.3584; D
-0.01, 0.06; 0.3947; D
-0.15, -0.01; 1.3700; C
-0.15, -0.01; 0.3831; C
0.00, -0.12; 1.2887; A
0.00, -0.12; 0.4412; A
0.02, -0.10; 0.8475; A
0.10, -0.04; 0.4760; B
0.10, -0.04; 0.3947; B
0.10, -0.04; 0.9172; B
0.10, -0.04; 0.8707; B
0.10, -0.04; 0.8475; B
0.12, -0.01; 0.9520; B
0.12, -0.01; 0.2438; B
0.12, -0.01; 0.6037; B
0.12, -0.01; 0.9288; B
0.12, -0.01; 0.2206; B
0.12, -0.01; 0.6153; B
-0.15, -0.01; 0.8359; C
-0.13, -0.01; 0.9172; C
-0.13, -0.01; 0.8591; C
-0.13, -0.01; 0.8708; C
-0.13, -0.01; 0.8707; C
-0.13, -0.01; 0.2206; C
-0.13, -0.01; 0.6385; C
-0.13, -0.01; 0.8708; C
-0.13, -0.01; 0.2322; C
-0.13, -0.01; 0.6269; C
-0.00, -0.09; 0.9172; A
-0.00, -0.08; 0.8824; A
-0.00, -0.08; 0.9288; A
-0.00, -0.08; 0.8243; A
-0.00, -0.08; 0.8475; A
-0.00, -0.08; 0.2438; A
-0.00, -0.08; 0.6153; A
-0.00, -0.08; 0.9404; A
-0.00, -0.08; 0.1858; A
-0.00, -0.08; 0.5921; A
-0.00, 0.07; 0.8824; D
-0.00, 0.07; 0.8359; D
-0.00, 0.07; 0.9636; D
-0.00, 0.07; 0.7895; D
-0.13, -0.03; 0.9056; C
0.02, -0.13; 0.9172; A
0.14, -0.03; 0.8359; B
0.14, -0.03; 0.2786; B
0.14, -0.03; 0.6385; B
0.01, 0.06; 0.8824; D
-0.12, -0.00; 0.8591; C
-0.00, -0.11; 0.8591; A
-0.00, -0.11; 0.2438; A
-0.00, -0.11; 0.6153; A
0.12, -0.02; 0.8475; B
0.01, 0.06; 0.9172; D
-0.14, -0.01; 0.8708; C
-0.14, -0.01; 0.2322; C
-0.14, -0.02; 0.6502; C
-0.01, -0.10; 0.8708; A
0.14, -0.03; 0.9288; B
0.01, 0.06; 0.8591; D
0.01, 0.06; 0.4412; D
0.01, 0.06; 0.3947; D
