#Musica 'green_hill_zone new.mp3' salva no diretorio 'green_hill_zone new'

-0.01, -0.06; 1.8141; A
-0.01, -0.06; 0.5457; A
-0.01, -0.06; 0.6502; A
-0.01, -0.06; 0.5805; A
-0.01, -0.06; 0.6502; A
-0.01, -0.06; 0.4412; A
-0.01, -0.06; 0.3831; A
-0.01, -0.06; 0.5805; A
-0.01, -0.06; 0.6502; A
-0.11, -0.02; 1.9737; C
-0.11, -0.02; 0.5921; C
-0.11, -0.02; 0.5224; C
0.10, -0.02; 0.5341; B
0.10, -0.02; 0.5108; B
0.12, -0.02; 0.5341; B
-0.02, 0.06; 0.5341; D
-0.02, 0.05; 0.4992; D
-0.00, -0.12; 1.9273; A
-0.01, -0.07; 0.2786; A
-0.00, 0.03; 0.4412; D
-0.08, 0.00; 0.7779; C
-0.08, 0.00; 0.2438; C
-0.08, 0.00; 0.4296; C
-0.08, 0.00; 0.1741; C
-0.08, 0.00; 0.3947; C
-0.08, 0.00; 0.1974; C
-0.08, 0.00; 0.3599; C
0.15, -0.01; 1.1842; B
0.15, -0.01; 0.1974; B
0.15, -0.01; 0.2090; B
0.15, -0.01; 0.4412; B
0.15, -0.01; 0.1742; B
0.15, -0.01; 0.4180; B
0.15, -0.01; 0.2206; B
0.15, -0.01; 0.3715; B
-0.15, -0.01; 1.3584; C
-0.15, -0.01; 0.1974; C
-0.15, -0.01; 0.4528; C
-0.15, -0.01; 0.1974; C
-0.15, -0.01; 0.3947; C
-0.15, -0.01; 0.2322; C
-0.15, -0.01; 0.3367; C
-0.01, -0.08; 1.2307; A
-0.01, -0.08; 0.1974; A
-0.01, -0.08; 0.1858; A
-0.01, -0.08; 0.4412; A
-0.01, -0.08; 0.1858; A
-0.01, -0.08; 0.4296; A
-0.01, -0.08; 0.2206; A
-0.01, -0.05; 0.3831; A
-0.01, 0.06; 1.3468; D
-0.01, 0.06; 0.1858; D
-0.01, 0.06; 0.4528; D
-0.01, 0.06; 0.2206; D
-0.01, 0.06; 0.4063; D
-0.01, 0.06; 0.2206; D
-0.01, 0.06; 0.3831; D
-0.00, -0.11; 1.1958; A
-0.00, -0.11; 0.2090; A
-0.00, -0.11; 0.1509; A
-0.00, -0.11; 0.4760; A
-0.00, -0.11; 0.1858; A
-0.00, -0.11; 0.3599; A
-0.00, -0.11; 0.2206; A
-0.00, -0.11; 0.3947; A
-0.15, -0.02; 1.3468; C
-0.15, -0.02; 0.1858; C
-0.15, -0.02; 0.4644; C
-0.15, -0.02; 0.1974; C
-0.15, -0.02; 0.3947; C
-0.15, -0.02; 0.1974; C
-0.15, -0.02; 0.3599; C
0.12, -0.01; 1.2074; B
0.12, -0.01; 0.1974; B
0.12, -0.01; 0.1742; B
0.12, -0.01; 0.4412; B
0.12, -0.01; 0.2090; B
0.12, -0.01; 0.3947; B
0.12, -0.01; 0.1974; B
0.12, -0.01; 0.3947; B
0.02, 0.02; 0.6269; B
-0.08, 0.01; 0.5921; C
-0.11, -0.04; 0.5573; C
-0.09, -0.09; 0.6037; C
-0.01, -0.13; 0.6269; A
0.06, -0.10; 0.4760; A
0.12, -0.04; 0.4528; B
0.13, 0.00; 0.5573; B
0.06, 0.05; 0.5805; B
-0.03, 0.06; 0.5341; D
-0.11, 0.05; 0.5689; C
-0.14, -0.05; 0.4644; C
-0.12, -0.10; 0.4180; C
-0.01, -0.14; 0.5689; A
0.08, -0.13; 0.5573; A
0.14, -0.07; 0.5573; B
0.11, -0.01; 0.6037; B
0.06, 0.02; 0.3483; B
-0.03, 0.04; 0.4063; D
-0.11, 0.03; 0.5689; C
-0.15, -0.03; 0.5805; C
-0.10, -0.10; 0.5805; C
0.01, -0.13; 0.5689; A
0.08, -0.07; 0.4760; B
0.04, 0.03; 0.5689; B
0.01, -0.09; 0.8127; A
0.01, -0.09; 0.2090; A
0.01, -0.09; 0.4063; A
0.01, -0.09; 0.2090; A
0.01, -0.09; 0.3947; A
0.01, -0.09; 0.2206; A
0.01, -0.09; 0.3831; A
-0.00, 0.06; 1.1146; D
-0.00, 0.06; 0.2322; D
-0.00, 0.06; 0.1741; D
-0.00, 0.06; 0.4644; D
-0.00, 0.06; 0.1742; D
-0.00, 0.06; 0.4296; D
-0.00, 0.06; 0.1858; D
-0.00, 0.06; 0.3715; D
0.00, -0.14; 1.3468; A
0.00, -0.14; 0.2206; A
0.00, -0.14; 0.4180; A
0.00, -0.14; 0.2090; A
0.00, -0.14; 0.4063; A
0.00, -0.14; 0.2090; A
0.00, -0.14; 0.3831; A
-0.00, 0.06; 1.1146; D
-0.00, 0.06; 0.2090; D
-0.00, 0.06; 0.2090; D
-0.00, 0.06; 0.4760; D
-0.00, 0.06; 0.1741; D
-0.00, 0.06; 0.4063; D
-0.00, 0.06; 0.2322; D
-0.00, 0.06; 0.3947; D
-0.15, -0.01; 1.3932; C
-0.15, -0.01; 0.1974; C
-0.15, -0.01; 0.4180; C
-0.15, -0.01; 0.2090; C
-0.15, -0.01; 0.4644; C
-0.15, -0.01; 0.2206; C
-0.15, -0.01; 0.3831; C
0.13, -0.02; 1.1030; B
0.13, -0.02; 0.1858; B
0.13, -0.02; 0.1974; B
0.13, -0.02; 0.4528; B
0.13, -0.02; 0.1858; B
0.13, -0.02; 0.3831; B
